from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .prompt_importer import (
    NODE_CLASS_MAPPINGS as PROMPT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PROMPT_NODE_DISPLAY_NAME_MAPPINGS,
)
from .workflow_export import (
    NODE_CLASS_MAPPINGS as WORKFLOW_EXPORT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as WORKFLOW_EXPORT_NODE_DISPLAY_NAME_MAPPINGS,
)
from .h3_live_preview import (
    NODE_CLASS_MAPPINGS as LIVE_PREVIEW_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LIVE_PREVIEW_NODE_DISPLAY_NAME_MAPPINGS,
)
from .dlss_neural_enhance import (
    NODE_CLASS_MAPPINGS as DLSS_ENHANCE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as DLSS_ENHANCE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .h3_face_refine_star7 import (
    NODE_CLASS_MAPPINGS as H3_FACE_REFINE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as H3_FACE_REFINE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .h3_latent_upscale_star7 import (
    NODE_CLASS_MAPPINGS as H3_LATENT_UPSCALE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as H3_LATENT_UPSCALE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .h3_stream_decode_star7 import (
    NODE_CLASS_MAPPINGS as H3_STREAM_DECODE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as H3_STREAM_DECODE_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS.update(PROMPT_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(PROMPT_NODE_DISPLAY_NAME_MAPPINGS)
NODE_CLASS_MAPPINGS.update(WORKFLOW_EXPORT_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(WORKFLOW_EXPORT_NODE_DISPLAY_NAME_MAPPINGS)
NODE_CLASS_MAPPINGS.update(LIVE_PREVIEW_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(LIVE_PREVIEW_NODE_DISPLAY_NAME_MAPPINGS)
NODE_CLASS_MAPPINGS.update(DLSS_ENHANCE_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(DLSS_ENHANCE_NODE_DISPLAY_NAME_MAPPINGS)
NODE_CLASS_MAPPINGS.update(H3_FACE_REFINE_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(H3_FACE_REFINE_NODE_DISPLAY_NAME_MAPPINGS)
NODE_CLASS_MAPPINGS.update(H3_LATENT_UPSCALE_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(H3_LATENT_UPSCALE_NODE_DISPLAY_NAME_MAPPINGS)
NODE_CLASS_MAPPINGS.update(H3_STREAM_DECODE_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(H3_STREAM_DECODE_NODE_DISPLAY_NAME_MAPPINGS)

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
